name: Version Update

description: Updates version and returns the new version

inputs:
  currentVersion:
    description: The current helm chart version.
    required: true
  currentAppVersion:
    description: The current app version.
    required: true
  updatedAppVersion:
    description: The next app version.
    required: true

outputs:
  newVersion:
    description: The new helm chart version.
    value: ${{ steps.set-new-version.outputs.step-result }}

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Version Update
      shell: bash
      id: set-new-version
      run: |
        ls
        version=$(node version-update.js ${{ inputs.currentVersion }} ${{ inputs.currentAppVersion }} ${{ inputs.updatedAppVersion }})
        echo "::set-output name=step-result::$version"
        echo "step-result=$version" >> $GITHUB_ENV