name: Update Chart Version and Open Pull Request

on:
  workflow_dispatch:

jobs:
  update-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Chart Version
        run: |
          yq e -i '.version="1.2.3"' Chart.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add Chart.yaml
          git commit -m "Update version and appVersion"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update version and appVersion"
          title: "Update version and appVersion"
          body: "This pull request updates the version and appVersion fields in Chart.yaml"
          branch: update-chart-version-${{ github.sha }}
          base: main
