name: Update Chart Version and Open Pull Request

on:
  workflow_dispatch:

permissions: write-all

env:
  CHART_DIRECTORY: 'charts/test-chart'
  TEST_VERSION: 'v1.5.7'

jobs:
  update-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set the versions in envs
        run: |
          DOCKER_IMAGE_TAG=$(echo "${TEST_VERSION}" | sed 's/^v//')
          echo docker tag v2 is: "$DOCKER_IMAGE_TAG"

      - name: Update Chart Version
        run: |
          yq e -i ".appVersion=$DOCKER_IMAGE_TAG" ${{ env.CHART_DIRECTORY }}/Chart.yaml
          UPDATED_APP_VERSION=$(yq e '.appVersion' "${{ env.CHART_DIRECTORY }}/Chart.yaml")
          echo "Updated appVersion: $UPDATED_APP_VERSION"
          echo "chart path is: ${{ env.CHART_DIRECTORY }}/Chart.yaml"

      - name: Debug PAT
        run: |
          echo "PAT: $PAT"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add ${{ env.CHART_DIRECTORY }}/Chart.yaml
          git commit -m "Update version and appVersion"

      - name: Push Changes
        run: git push
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     commit-message: "Update version and appVersion"
      #     title: "Update version and appVersion"
      #     body: "This pull request updates the version and appVersion fields in Chart.yaml"
      #     branch: update-chart-version-${{ github.sha }}
      #     base: main


  # git push origin ${{ github.event.repository.default_branch }}