name: Update Chart Version and Open Pull Request

on:
  workflow_dispatch:

permissions: write-all

jobs:
  update-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Chart Version
        run: |
          yq e -i '.version="1.2.10"' Chart.yaml
          yq e -i '.appVersion="5.6.10"' Chart.yaml

      - name: Debug PAT
        run: |
          echo "PAT: $PAT"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add Chart.yaml
          git commit -m "Update version and appVersion"
          git push origin ${{ github.event.repository.default_branch }}
        env:
          PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      #     commit-message: "Update version and appVersion"
      #     title: "Update version and appVersion"
      #     body: "This pull request updates the version and appVersion fields in Chart.yaml"
      #     branch: update-chart-version-${{ github.sha }}
      #     base: main
