name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for unordered list in changelog
        run: |
          if grep -E "^\s*-\s" ./CHANGELOG.md; then
            echo "Changelog is valid: Unordered list items found."
          else
            echo "Changelog is invalid: No unordered list items found."
            exit 1
          fi